
hist:
	gcc -Wall -O3 -s -static hist.c -o hist -lm

imgen:
	gcc -Wall -O3 -s -static imgen.c -o imgen -lm

psnr:
	gcc -Wall -O3 -s -static psnr.c -o psnr -lm

ssim:
	gcc -Wall -O3 -s -static ssim.c -o ssim -lm

wavpsnr:
	gcc -Wall -O3 -s -static wavpsnr.c -o wavpsnr -lm

diff:
	gcc -Wall -O3 -s -static diff.c -o diff -lm

chism:
	gcc -Wall -O3 -mavx2 -mbmi -mlzcnt -s -static chism.c -o chism -lm
