#version 460
layout(local_size_x=1, local_size_y=1) in;
layout(std430, binding=0) buffer lay0 { int inbuf[]; };
layout(std430, binding=1) buffer lay1 { int outbuf[]; };

void main()
{
	const uint idx=gl_GlobalInvocationID.x;
	outbuf[idx]=inbuf[idx]+inbuf[idx];
}


//#extension GL_EXT_debug_printf : require
//void main()
//{
//	debugPrintfEXT("\'Hello World\' (said thread %d)\n", gl_GlobalInvocationID.x);
//}